image: ruby:2.6.3

before_script:
  - gem install bundler:2.0.2
  - bundle install

pages:
  script:
  - bundle install
  - bundle exec jekyll build -d public
  artifacts:
    paths:
    - public
  only:
  - develop
