---
title: Wdr
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
    permalink: /updates/:title.html
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    page_title: Updates
plugins:
- jekyll-paginate
paginate: 10
paginate_path: "/updates/:num/"
baseurl: "/wdr"
footer:
  facebook:
    isActive: true
    url: facebook.com
  twitter:
    isActive: true
    twitter.com:
  address:
    title: Lorem Ipsum
    text: |-
      13/4, Sum dolor sit amet,
      Consec tetur, Adipisicing,
      Incididuntut - 234556
    phone: "+91-9876543210"
    email: sber@example.com
