---
title: Wdr
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  test:
    title: Test
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    page_title: Updates
plugins:
- jekyll-paginate
paginate: 10
paginate_path: "/updates/:num/"
baseurl: "/wdr"
