defaults:
  -
    scope:
      path: ""
    values:
        layout: "default"
    scope:
      path: ""
      type: "posts"
    values:
        page_title: "Updates"

plugins: [jekyll-paginate]

paginate: 10
paginate_path: "/updates/:num/"
baseurl: "/wdr"
collections:
  posts:
    output: true
    permalink: /:title.html